# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WorldDomination
                                 A QGIS plugin
 Strategy game
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-16
        copyright            : (C) 2024 by Gwennaël François
        email                : gwennaelfrancois@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WorldDomination class from file WorldDomination.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .world_domination import WorldDomination
    return WorldDomination(iface)
